### ISSUE TITLE
User menu cut off

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1978]
The user menu is cut off on the side of the page in the default theme

![Screen Shot 2022-03-17 at 9.04.33 AM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/a66310b6-28b5-4bf7-9782-0b306254bf1a)

**Comment by robyngit** [comment]
Related: #1598

**Comment by robyngit** [comment]
See https://github.com/NCEAS/metacatui-themes/issues/12

**Comment by iannesbitt** [comment]
This issue can be solved by adding the following to `metacatui.css` under the heading `/* Logged-in view and user controls in navbar */`

```css
    /* Keep logged-in nav dropdown from going off page right */
    .navbar-inner .dropdown-menu {
        left: unset;
        right: 0;
    }
```

I will create a PR for this shortly.
