### ISSUE TITLE
Set k8s container resources requests & limits for MetacatUI

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacatui#2640]
For k8s deployments of MetacatUI, we need to set realistic values the following, so the container does not get `OOMKilled`:

```yaml
spec:
  containers:
    resources:
      requests:
        cpu: #value
        memory: #value
    limits:
      cpu: #value
      memory: #value
```
